### ISSUE TITLE
Embedded Checkout

### ISSUE THREAD

**Issue by tborba1** [gdg-modesto/devfest22#10]
From Daisy: Here is the code we would use for that

`<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script> <script type="text/javascript"> var exampleCallback = function() { console.log('Order complete!'); }; window.EBWidgets.createWidget({ // Required widgetType: 'checkout', eventId: '404767429277', iframeContainerId: 'eventbrite-widget-container-404767429277', // Optional iframeContainerHeight: 425, // Widget height in pixels. Defaults to a minimum of 425px if not provided onOrderComplete: exampleCallback // Method called when an order has successfully completed }); </script>`

Here is the instructions on how embedded check out works: https://www.eventbrite.com/support/articles/en_US/Multi_Group_How_To/how-to-sell-eventbrite-tickets-on-your-website-through-an-embedded-checkout

**Comment by daisymayorga-galtechs** [comment]
<div id="eventbrite-widget-container-404767429277"></div>

<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '404767429277',
        iframeContainerId: 'eventbrite-widget-container-404767429277',

        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>

**Comment by daisymayorga-galtechs** [comment]
`<div id="eventbrite-widget-container-404767429277"></div>

<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '404767429277',
        iframeContainerId: 'eventbrite-widget-container-404767429277',

        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>`

**Comment by daisymayorga-galtechs** [comment]
`<div id="eventbrite-widget-container-404767429277"></div>

<script src="https://www.eventbrite.com/static/widgets/eb_widgets.js"></script>

<script type="text/javascript">
    var exampleCallback = function() {
        console.log('Order complete!');
    };

    window.EBWidgets.createWidget({
        // Required
        widgetType: 'checkout',
        eventId: '404767429277',
        iframeContainerId: 'eventbrite-widget-container-404767429277',

        // Optional
        iframeContainerHeight: 425,  // Widget height in pixels. Defaults to a minimum of 425px if not provided
        onOrderComplete: exampleCallback  // Method called when an order has successfully completed
    });
</script>`

**Comment by tborba1** [comment]
Per Daisy via LinkedIn chat on 9/13/2022:
likely does not work via local host, may need to commit code to view on https site

**Comment by tborba1** [comment]
added embedded checkout for review
dee7c86010963d53dd8eb090a4d38df78fbd207c

**Comment by tborba1** [comment]
Per 9/19/2022 Meeting:

- [ ] Embedded Checkout to be included on speakers.html page below Speaker Cards
- [ ] "Register" Button/Modal to be updated in the Hero Section

**Comment by tborba1** [comment]
911cd0bd1264eec6363357880c6ca7ec0bbe256f
