### ISSUE TITLE
Sponsors Section - Details

### ISSUE THREAD

**Issue by tborba1** [gdg-modesto/devfest22#19]
- Should each sponsor’s logo link to their website? No
- Need list of sponsors and logo to be used for each: see comment below
- Need link for “Become a Sponsor” button: No

**Comment by daisymayorga-galtechs** [comment]
![BWI_Icon](https://user-images.githubusercontent.com/68982348/190878626-32e664b4-4a7e-499c-acd2-68a0e7b48e1f.png)
![google-logo-png-google-sva-scholarship-20](https://user-images.githubusercontent.com/68982348/190878628-1d0186ce-76b3-4763-8aa5-4aa181a36aeb.png)
![INvestInMe](https://user-images.githubusercontent.com/68982348/190878629-3e8610c5-bd56-4077-b4e0-7a73c818f032.png)
![StanCounty](https://user-images.githubusercontent.com/68982348/190878630-018d7e59-9f4d-417a-
![bay valley tech logo](https://user-images.githubusercontent.com/68982348/190878657-0b99d88d-e9e2-433a-b7bb-c8db18c631f3.png)
89b4-40d2e7cac4b5.png)
![STEM Logo Final V3](https://user-images.githubusercontent.com/68982348/190878631-e5c8702c-41a9-4db0-bd63-5e8e7a324429.png)

**Comment by tborba1** [comment]
- [ ] Bitwise
- [ ] Google
- [ ] Invest In Me
- [ ] Stanislaus County Office of Education
- [ ] Bay Valley Tech

**Comment by tborba1** [comment]
- [ ] "Become a Sponsor" button

**Comment by tborba1** [comment]
dbbb26c5cce796bd3eeb9ee27da255e460b56875

**Comment by tborba1** [comment]
Update Bitwise Logo: 
![image](https://user-images.githubusercontent.com/100311616/193478272-0f30b2fc-8d3d-423a-b6b1-cba394eeda11.png)

**Comment by tborba1** [comment]
129aee246a392b868636d82642f357038c9798bb
