### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by tborba1** [gdg-modesto/devfest22#9]
Create Footer to include:

Explore:
- [x] GDG Modesto (https://gdg.community.dev/gdg-modesto/)
- [x] WTM Modesto (https://www.wtmmodesto.com/)

Community:
- [x] WTM About (https://www.wtmmodesto.com/#mu-about)

Follow Us:
- [x] Facebook (https://www.facebook.com/wtmmodesto)
- [x] Instagram (https://www.instagram.com/wtmmodesto/)
- [x] LinkedIn (https://www.linkedin.com/company/women-techmakers-modesto/)

**Comment by tborba1** [comment]
Community section should include Volunteer
Need link from @daisymayorga-galtechs

**Comment by daisymayorga-galtechs** [comment]
Link for Volunteer form: https://docs.google.com/forms/d/e/1FAIpQLSc-AV-zQX1npy-hzeoc_Q9rLlNx64zQ3FuvzgF2xOz9p6e1Fw/viewform?usp=sf_link

@tborba1

**Comment by tborba1** [comment]
Dev: 48236a55fb1164a07dd79cf90abe3d12f139b697
